# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRFwqMzkty0XW7uEADmnJKtz15tbPlKC

#Between Fall 2021 and Fall 2025 (time window), how did the freshman admit rate for Asian applicants at UC Santa Cruz (population of interest) change, measured in percentage point difference (metric being measured)?
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="UCSC Asian Freshman Admit Rate",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="collapsed"
)

st.markdown("""
<style>
.block-container {
    padding-top: 1.5rem;
    padding-bottom: 0.5rem;
    padding-left: 1.8rem;
    padding-right: 1.8rem;
    max-width: 100%;
}

h1 {
    font-size: 1.9rem !important;
    margin-bottom: 0.1rem !important;
}

h2, h3, h4 {
    margin-top: 0.2rem !important;
    margin-bottom: 0.2rem !important;
}

[data-testid="stMetric"] {
    padding: 0.25rem 0.5rem;
}

[data-testid="stMetricValue"] {
    font-size: 1.6rem;
}

[data-testid="stMetricLabel"] {
    font-size: 0.9rem;
}

#MainMenu {
    visibility: hidden;
}

footer {
    visibility: hidden;
}
</style>
""", unsafe_allow_html=True)


# ============================================================
# LOAD DATA
# ============================================================

DATA_FILE = (
    Path(__file__).parent /
    "uc_admissions_summary_by_ethnicity.csv"
)

@st.cache_data
def load_data():
    return pd.read_csv(DATA_FILE)

try:
    df = load_data()

except Exception as e:
    st.error("Could not load the admissions dataset.")
    st.exception(e)
    st.stop()


# ============================================================
# CLEAN DATA
# ============================================================

df["fall_term"] = pd.to_numeric(
    df["fall_term"],
    errors="coerce"
)

df["n"] = pd.to_numeric(
    df["n"],
    errors="coerce"
)

df["entrant_level"] = (
    df["entrant_level"]
    .astype(str)
    .str.strip()
    .str.lower()
)

df["campus"] = (
    df["campus"]
    .astype(str)
    .str.strip()
)

df["ethnicity"] = (
    df["ethnicity"]
    .astype(str)
    .str.strip()
)

df["count_type"] = (
    df["count_type"]
    .astype(str)
    .str.strip()
)


# ============================================================
# FIX POPULATION TO THE RESEARCH QUESTION
# ============================================================

question_data = df[
    (df["entrant_level"] == "freshman")
    & (df["campus"] == "Santa Cruz")
    & (df["ethnicity"] == "Asian")
    & (df["count_type"].isin(["App", "Adm"]))
].copy()


# ============================================================
# BUILD SUMMARY
# ============================================================

summary = question_data.pivot_table(
    index="fall_term",
    columns="count_type",
    values="n",
    aggfunc="sum"
).reset_index()

summary = summary.dropna(
    subset=["fall_term"]
)

summary = summary.sort_values(
    "fall_term"
)

summary["admit_rate"] = (
    summary["Adm"] /
    summary["App"]
) * 100

summary["admit_rate"] = (
    summary["admit_rate"]
    .round(2)
)


# ============================================================
# AVAILABLE YEARS
# ============================================================

available_years = (
    summary["fall_term"]
    .astype(int)
    .tolist()
)

if 2021 not in available_years or 2025 not in available_years:
    st.error(
        "The dataset does not contain both Fall 2021 "
        "and Fall 2025 for this population."
    )
    st.stop()


# ============================================================
# HEADER
# ============================================================

st.title("🎓 UC Santa Cruz Asian Freshman Admit Rate")

st.caption(
    "Research question: How did the freshman admit rate for "
    "Asian applicants change between Fall 2021 and Fall 2025?"
)


# ============================================================
# INTERACTIVE CONTROLS
# ============================================================

control1, control2, control3 = st.columns(
    [1, 1, 1.4]
)

with control1:

    start_year = st.selectbox(
        "Start year",
        available_years,
        index=available_years.index(2021)
    )

with control2:

    valid_end_years = [
        y for y in available_years
        if y > start_year
    ]

    if not valid_end_years:
        st.warning(
            "Choose an earlier start year."
        )
        st.stop()

    default_end = (
        valid_end_years.index(2025)
        if 2025 in valid_end_years
        else len(valid_end_years) - 1
    )

    end_year = st.selectbox(
        "End year",
        valid_end_years,
        index=default_end
    )

with control3:

    chart_view = st.radio(
        "View",
        [
            "Admit Rate",
            "Applicants vs. Admits"
        ],
        horizontal=True
    )


# ============================================================
# SELECT PERIOD
# ============================================================

period = summary[
    summary["fall_term"].between(
        start_year,
        end_year
    )
].copy()

start_row = period[
    period["fall_term"] == start_year
].iloc[0]

end_row = period[
    period["fall_term"] == end_year
].iloc[0]


# ============================================================
# CALCULATIONS
# ============================================================

start_rate = start_row["admit_rate"]
end_rate = end_row["admit_rate"]

pp_change = (
    end_rate - start_rate
)

start_apps = start_row["App"]
end_apps = end_row["App"]

start_admits = start_row["Adm"]
end_admits = end_row["Adm"]

app_growth = (
    (end_apps / start_apps) - 1
) * 100

admit_growth = (
    (end_admits / start_admits) - 1
) * 100


# ============================================================
# KPI ROW
# ============================================================

k1, k2, k3, k4 = st.columns(4)

k1.metric(
    f"{start_year} Admit Rate",
    f"{start_rate:.2f}%"
)

k2.metric(
    f"{end_year} Admit Rate",
    f"{end_rate:.2f}%"
)

k3.metric(
    "Percentage-Point Change",
    f"{pp_change:+.2f} pp"
)

k4.metric(
    "Admit Growth",
    f"{admit_growth:+.1f}%"
)


# ============================================================
# MAIN CONTENT
# ============================================================

left, right = st.columns(
    [1.55, 0.75]
)


# ============================================================
# MAIN CHART
# ============================================================

with left:

    if chart_view == "Admit Rate":

        st.markdown(
            "#### Admit Rate Over Time"
        )

        fig, ax = plt.subplots(
            figsize=(7.5, 3.2)
        )

        ax.plot(
            period["fall_term"],
            period["admit_rate"],
            marker="o",
            linewidth=2
        )

        ax.set_xlabel(
            "Fall Term"
        )

        ax.set_ylabel(
            "Admit Rate (%)"
        )

        ax.set_xticks(
            period["fall_term"]
        )

        low = max(
            0,
            period["admit_rate"].min() - 8
        )

        high = min(
            100,
            period["admit_rate"].max() + 8
        )

        ax.set_ylim(
            low,
            high
        )

        ax.grid(
            axis="y",
            alpha=0.25
        )

        for year, rate in zip(
            period["fall_term"],
            period["admit_rate"]
        ):

            ax.annotate(
                f"{rate:.1f}%",
                (year, rate),
                xytext=(0, 7),
                textcoords="offset points",
                ha="center",
                fontsize=9
            )

        fig.tight_layout()

        st.pyplot(
            fig,
            use_container_width=True
        )

        plt.close(fig)


    else:

        st.markdown(
            "#### Applicants vs. Admits"
        )

        fig, ax = plt.subplots(
            figsize=(7.5, 3.2)
        )

        x = list(
            range(len(period))
        )

        width = 0.35

        ax.bar(
            [
                i - width / 2
                for i in x
            ],
            period["App"],
            width,
            label="Applicants"
        )

        ax.bar(
            [
                i + width / 2
                for i in x
            ],
            period["Adm"],
            width,
            label="Admits"
        )

        ax.set_xticks(x)

        ax.set_xticklabels(
            period["fall_term"]
            .astype(int)
        )

        ax.set_xlabel(
            "Fall Term"
        )

        ax.set_ylabel(
            "Number of Students"
        )

        ax.legend(
            frameon=False
        )

        ax.grid(
            axis="y",
            alpha=0.2
        )

        fig.tight_layout()

        st.pyplot(
            fig,
            use_container_width=True
        )

        plt.close(fig)


# ============================================================
# RIGHT-SIDE INTERPRETATION
# ============================================================

with right:

    st.markdown(
        "#### What changed?"
    )

    if pp_change > 0:

        direction = "increased"
        symbol = "▲"

    elif pp_change < 0:

        direction = "decreased"
        symbol = "▼"

    else:

        direction = "did not change"
        symbol = "—"

    st.metric(
        "Overall Change",
        f"{symbol} {abs(pp_change):.2f} pp"
    )

    st.write(
        f"""
        The freshman admit rate for **Asian applicants
        at UC Santa Cruz** {direction} from
        **{start_rate:.2f}%** in Fall {start_year}
        to **{end_rate:.2f}%** in Fall {end_year}.
        """
    )

    st.write(
        f"""
        Applications changed by
        **{app_growth:+.1f}%**, while admits changed by
        **{admit_growth:+.1f}%**.
        """
    )

    if admit_growth > app_growth:

        st.success(
            "Admits grew faster than applications, "
            "which helped raise the admit rate."
        )

    elif admit_growth < app_growth:

        st.warning(
            "Applications grew faster than admits, "
            "which pushed the admit rate downward."
        )


# ============================================================
# FOOTER / METHODOLOGY
# ============================================================

with st.expander(
    "Methodology"
):

    st.markdown(
        """
        **Population:** Asian freshman applicants at
        UC Santa Cruz.

        **Admit Rate**

        `Admits ÷ Applicants × 100`

        **Percentage-Point Difference**

        `End-Year Admit Rate − Start-Year Admit Rate`

        The default comparison is Fall 2021 to Fall 2025,
        which directly answers the research question.
        """
    )